export const users = [
  {
    gamertag: "DortCeL",
    name: "Ismail AliF",
    age: 22,
    nationality: "Bangladesh",
    gender: "Male",
  },
  {
    gamertag: "PewDiePie",
    name: "John Smith",
    age: 25,
    nationality: "Sweden",
    gender: "Male",
  },
  {
    gamertag: "Ninja",
    name: "Jane Doe",
    age: 30,
    nationality: "USA",
    gender: "Female",
  },
  {
    gamertag: "Shroud",
    name: "Michael Johnson",
    age: 28,
    nationality: "Canada",
    gender: "Male",
  },
  {
    gamertag: "Kingslayer",
    name: "Munem Al Shafat",
    age: 69,
    nationality: "Bangladesh",
    gender: "Gay",
  },

  {
    gamertag: "Pokimane",
    name: "Emily Davis",
    age: 22,
    nationality: "Canada",
    gender: "Female",
  },
  {
    gamertag: "Summit1g",
    name: "Chris Lee",
    age: 35,
    nationality: "USA",
    gender: "Male",
  },
  {
    gamertag: "Faker",
    name: "Kim Jong-un",
    age: 24,
    nationality: "South Korea",
    gender: "Male",
  },
  {
    gamertag: "PunkIzzOver",
    name: "Izaz Alam",
    age: 23,
    nationality: "Bangladesh",
    gender: "Male",
  },
  {
    gamertag: "xQc",
    name: "Félix Lengyel",
    age: 27,
    nationality: "Canada",
    gender: "Male",
  },
  {
    gamertag: "DrDisrespect",
    name: "Herschel Beahm IV",
    age: 35,
    nationality: "USA",
    gender: "Male",
  },
  {
    gamertag: "Sodapoppin",
    name: "Chance Morris",
    age: 26,
    nationality: "USA",
    gender: "Male",
  },
  {
    gamertag: "Boostwar",
    name: "Samiul Bashar",
    age: 16,
    nationality: "Bangladesh",
    gender: "Male",
  },
  {
    gamertag: "Sykkuno",
    name: "Thomas Sylvester",
    age: 29,
    nationality: "USA",
    gender: "Male",
  },
  {
    gamertag: "PewDiePie",
    name: "Alice Johnson",
    age: 24,
    nationality: "Sweden",
    gender: "Female",
  },
  {
    gamertag: "Ninja",
    name: "Bob Smith",
    age: 33,
    nationality: "USA",
    gender: "Male",
  },
  {
    gamertag: "Shroud",
    name: "Charlie Brown",
    age: 27,
    nationality: "Canada",
    gender: "Male",
  },
  {
    gamertag: "Pokimane",
    name: "David Wilson",
    age: 22,
    nationality: "Canada",
    gender: "Male",
  },
  {
    gamertag: "Summit1g",
    name: "Eva White",
    age: 35,
    nationality: "USA",
    gender: "Female",
  },
  {
    gamertag: "Faker",
    name: "Grace Kim",
    age: 24,
    nationality: "South Korea",
    gender: "Female",
  },
  {
    gamertag: "xQc",
    name: "Harry Potter",
    age: 27,
    nationality: "Canada",
    gender: "Male",
  },
  {
    gamertag: "DrDisrespect",
    name: "Ivy Thompson",
    age: 35,
    nationality: "USA",
    gender: "Female",
  },
  {
    gamertag: "Sodapoppin",
    name: "Jack Daniels",
    age: 26,
    nationality: "USA",
    gender: "Male",
  },
  {
    gamertag: "Sykkuno",
    name: "Kathy Green",
    age: 29,
    nationality: "USA",
    gender: "Female",
  },
  {
    gamertag: "PewDiePie",
    name: "Liam Johnson",
    age: 25,
    nationality: "Sweden",
    gender: "Male",
  },
  {
    gamertag: "Ninja",
    name: "Mia Wong",
    age: 30,
    nationality: "USA",
    gender: "Female",
  },
  {
    gamertag: "Shroud",
    name: "Noah King",
    age: 28,
    nationality: "Canada",
    gender: "Male",
  },
  {
    gamertag: "Pokimane",
    name: "Olivia Martinez",
    age: 22,
    nationality: "Canada",
    gender: "Female",
  },
  {
    gamertag: "Summit1g",
    name: "Paul Roberts",
    age: 35,
    nationality: "USA",
    gender: "Male",
  },
  {
    gamertag: "Faker",
    name: "Quinn Lee",
    age: 24,
    nationality: "South Korea",
    gender: "Male",
  },
  {
    gamertag: "xQc",
    name: "Ryan Adams",
    age: 27,
    nationality: "Canada",
    gender: "Male",
  },
  {
    gamertag: "DrDisrespect",
    name: "Sophia Lewis",
    age: 35,
    nationality: "USA",
    gender: "Female",
  },
  {
    gamertag: "Sodapoppin",
    name: "Tyler White",
    age: 26,
    nationality: "Bangladesh",
    gender: "Male",
  },
];
